
package com.adidas.sef.ws.model;

import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;




/**
 * WSDL File for Model Services
 * 
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ModelWs", targetNamespace = "http://www.adidas.com/sef/ws/model", wsdlLocation = "")
public class ModelWs_Service
    extends Service
{

    private final static URL MODELWS_WSDL_LOCATION;
    private final static WebServiceException MODELWS_EXCEPTION;
    private final static QName MODELWS_QNAME = new QName("http://www.adidas.com/sef/ws/model", "ModelWs");

    static {
        URL url = null;
        WebServiceException e = null;
        //try {
           // url = new URL("file:/D:/Satheesh/Satheesh_SystemExcellence/MP_PDC/ESB-WSDLs/ModelService.wsdl");
              url = ModelWs_Service.class.getClassLoader().getResource("ModelService.wsdl");
           
       /* } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }*/
        MODELWS_WSDL_LOCATION = url;
        MODELWS_EXCEPTION = e;
    }

    public ModelWs_Service() {
        super(__getWsdlLocation(), MODELWS_QNAME);
    }

    public ModelWs_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), MODELWS_QNAME, features);
    }

    public ModelWs_Service(URL wsdlLocation) {
        super(wsdlLocation, MODELWS_QNAME);
    }
    
    public ModelWs_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, MODELWS_QNAME, features);
    }

    public ModelWs_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

   /* public ModelWs_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }*/

    /**
     * 
     * @return
     *     returns ModelWs
     */
    @WebEndpoint(name = "ModelPort")
    public ModelWs getModelPort() {
        return super.getPort(new QName("http://www.adidas.com/sef/ws/model", "ModelPort"), ModelWs.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ModelWs
     */
    @WebEndpoint(name = "ModelPort")
    public ModelWs getModelPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.adidas.com/sef/ws/model", "ModelPort"), ModelWs.class, features);
    }

    private static URL __getWsdlLocation() {
        if (MODELWS_EXCEPTION!= null) {
            throw MODELWS_EXCEPTION;
        }
        return MODELWS_WSDL_LOCATION;
    }

}
