
package com.adidas.sef.ws.model;

import javax.xml.ws.WebFault;
import com.adidas.sef.ws.schema.commondata.SystemExcellenceException;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "systemExcellenceException", targetNamespace = "http://www.adidas.com/sef/ws/schema/commondata")
public class SystemExcellenceFaultMessage
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private SystemExcellenceException faultInfo;

    /**
     * 
     * @param message
     * @param faultInfo
     */
    public SystemExcellenceFaultMessage(String message, SystemExcellenceException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param message
     * @param faultInfo
     * @param cause
     */
    public SystemExcellenceFaultMessage(String message, SystemExcellenceException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: com.adidas.sef.ws.schema.commondata.SystemExcellenceException
     */
    public SystemExcellenceException getFaultInfo() {
        return faultInfo;
    }

}
