
package com.adidas.sef.ws.article;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;




import com.adidas.sef.ws.model.SystemExcellenceFaultMessage;
import com.adidas.sef.ws.schema.articledata.UpdateArticleRequests;
import com.adidas.sef.ws.schema.articledata.UpdateArticleResponse;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ArticleWs", targetNamespace = "http://www.adidas.com/sef/ws/article")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    com.adidas.sef.ws.schema.articledata.ObjectFactory.class,
    com.adidas.sef.ws.schema.articledata.ObjectFactory.class
})
public interface ArticleWs {


   
    /**
     * 
     * @param updateArticleReqs
     * @return
     *     returns com.adidas.sef.ws.schema.articledata.UpdateArticleResponse
     * @throws SystemExcellenceFaultMessage
     */
    @WebMethod(action = "http://www.adidas.com/sef/ws/updateArticles")
    @WebResult(name = "updateArticleResponse", targetNamespace = "http://www.adidas.com/sef/ws/schema/articledata", partName = "updateArticleRes")
    public UpdateArticleResponse updateArticles(
        @WebParam(name = "updateArticleRequests", targetNamespace = "http://www.adidas.com/sef/ws/schema/articledata", partName = "updateArticleReqs")
        UpdateArticleRequests updateArticleReqs)
        throws SystemExcellenceFaultMessage
    ;

   

}
