
package com.adidas.sef.ws.article;

import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;

import com.adidas.sef.ws.model.ModelWs_Service;


/**
 * WSDL File for Article Services
 * 
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ArticleWs", targetNamespace = "http://www.adidas.com/sef/ws/article", wsdlLocation = "")
public class ArticleWs_Service
    extends Service
{

    private final static URL ARTICLEWS_WSDL_LOCATION;
    private final static WebServiceException ARTICLEWS_EXCEPTION;
    private final static QName ARTICLEWS_QNAME = new QName("http://www.adidas.com/sef/ws/article", "ArticleWs");

    static {
        URL url = null;
        WebServiceException e = null;
       // try {
           // url = new URL("file:/D:/Satheesh/Satheesh_SystemExcellence/MP_PDC/ESB-WSDLs/ArticleService.wsdl");
            url = ArticleWs_Service.class.getClassLoader().getResource("ArticleService.wsdl");
       /* } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }*/
        ARTICLEWS_WSDL_LOCATION = url;
        ARTICLEWS_EXCEPTION = e;
    }

    public ArticleWs_Service() {
        super(__getWsdlLocation(), ARTICLEWS_QNAME);
    }

    public ArticleWs_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), ARTICLEWS_QNAME, features);
    }

    public ArticleWs_Service(URL wsdlLocation) {
        super(wsdlLocation, ARTICLEWS_QNAME);
    }

    public ArticleWs_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, ARTICLEWS_QNAME, features);
    }

    public ArticleWs_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ArticleWs_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ArticleWs
     */
    @WebEndpoint(name = "ArticlePort")
    public ArticleWs getArticlePort() {
        return super.getPort(new QName("http://www.adidas.com/sef/ws/article", "ArticlePort"), ArticleWs.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ArticleWs
     */
    @WebEndpoint(name = "ArticlePort")
    public ArticleWs getArticlePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.adidas.com/sef/ws/article", "ArticlePort"), ArticleWs.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ARTICLEWS_EXCEPTION!= null) {
            throw ARTICLEWS_EXCEPTION;
        }
        return ARTICLEWS_WSDL_LOCATION;
    }

}
